/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyPalmVillaRouteImport } from './routes/property.palm-villa'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyPalmVillaRoute = PropertyPalmVillaRouteImport.update({
  id: '/property/palm-villa',
  path: '/property/palm-villa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/property/palm-villa': typeof PropertyPalmVillaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/property/palm-villa': typeof PropertyPalmVillaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/property/palm-villa': typeof PropertyPalmVillaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/property/palm-villa'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/property/palm-villa'
  id: '__root__' | '/' | '/property/palm-villa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PropertyPalmVillaRoute: typeof PropertyPalmVillaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/palm-villa': {
      id: '/property/palm-villa'
      path: '/property/palm-villa'
      fullPath: '/property/palm-villa'
      preLoaderRoute: typeof PropertyPalmVillaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PropertyPalmVillaRoute: PropertyPalmVillaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
